import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

// ─── API Key Rotation ─────────────────────────────────────────────────────────
const API_KEYS = [
  process.env.GEMINI_API_KEY_1,
  process.env.GEMINI_API_KEY_2,
  process.env.GEMINI_API_KEY_3,
].filter(Boolean); // remove any undefined keys

const MODEL = 'gemini-2.5-flash';

function geminiUrl(key) {
  return `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${key}`;
}

// Try each API key in order until one succeeds (not 429/400/expired)
async function callGeminiWithKeyRotation(body) {
  let lastError = null;

  for (let i = 0; i < API_KEYS.length; i++) {
    const key = API_KEYS[i];
    console.log(`🔑 Trying API key ${i + 1}/${API_KEYS.length}...`);

    try {
      const res = await fetch(geminiUrl(key), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (res.ok) {
        console.log(`✅ Key ${i + 1} succeeded.`);
        return { res, ok: true };
      }

      const status = res.status;
      const errText = await res.text();

      // 429 = quota/rate limit, 400 with API_KEY_INVALID = expired key → try next
      if (status === 429 || (status === 400 && errText.includes('API_KEY_INVALID'))) {
        console.log(`⚠️  Key ${i + 1} failed (${status}) — trying next key...`);
        lastError = { status, errText };
        continue;
      }

      // Any other error — return it directly, no point trying other keys
      return { res: null, ok: false, status, errText };

    } catch (err) {
      console.log(`⚠️  Key ${i + 1} threw error: ${err.message} — trying next key...`);
      lastError = { status: 500, errText: err.message };
      continue;
    }
  }

  // All keys exhausted
  return {
    ok: false,
    status: 429,
    errText: lastError?.errText || 'All API keys exhausted. Please try again in a few minutes.'
  };
}

// ─── Parse Gemini JSON response safely ───────────────────────────────────────
async function parseGeminiResponse(res) {
  const geminiData = await res.json();
  let rawText = geminiData?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!rawText) {
    const finishReason = geminiData?.candidates?.[0]?.finishReason;
    if (finishReason) {
      console.error("❌ Gemini blocked request. Reason:", finishReason);
      return { error: `Gemini API blocked request: ${finishReason}` };
    }
    return { error: 'Empty response from Gemini API.' };
  }

  rawText = rawText.replace(/```json\n?/gi, '').replace(/```\n?/g, '').trim();
  const jsonMatch = rawText.match(/\{[\s\S]*\}/);
  const textToParse = jsonMatch ? jsonMatch[0] : rawText;

  try {
    const parsed = JSON.parse(textToParse);
    return { parsed };
  } catch (err) {
    console.error("❌ Strict parse failed, trying lax parse. Error:", err.message);
    try {
      // Clean up common JSON errors like trailing commas
      let cleanText = textToParse.replace(/,\s*([\]}])/g, '$1');
      
      const parsed = JSON.parse(cleanText);
      return { parsed };
    } catch (err2) {
      try {
        // Last resort: eval to allow unquoted keys or single quotes
        const evalParsed = (new Function(`return ${textToParse}`))();
        return { parsed: evalParsed };
      } catch (err3) {
        console.error("❌ All parsing failed. Raw output from Gemini was:", rawText);
        return { error: 'Failed to parse Gemini response.' };
      }
    }
  }
}

// ─── Warmup endpoint ──────────────────────────────────────────────────────────
app.get('/api/warmup', (req, res) => {
  res.json({ warmed: true, keys: API_KEYS.length, model: MODEL });
});

// ─── POST /api/analyze — Fake news detection ──────────────────────────────────
app.post('/api/analyze', async (req, res) => {
  const { text } = req.body;

  if (!text || !text.trim()) {
    return res.status(400).json({ error: 'No text provided.' });
  }

  if (API_KEYS.length === 0) {
    return res.status(500).json({ error: 'No API keys configured.' });
  }

  const PROMPT = `You are an advanced fake news and AI text detection engine.
You must meticulously analyze the provided text for:
1. Fake News or false claims.
2. AI-generated text patterns (ChatGPT/Claude/Gemini style content).
3. Scam or misleading job postings (e.g., massive salaries, no interviews, vague details).

If the text appears to be generated by AI, contains AI hallmarks, or looks like a scam/fake news, you MUST classify the verdict as "FAKE". Only give "REAL" if the text is definitively proven factual and written by a human.

Return ONLY valid JSON, no markdown. Use this structure:
{
  "verdict": "REAL" or "FAKE",
  "confidence": number (1-100),
  "explanation": "Detailed explanation of why it is real or fake/AI-generated.",
  "corrected_fact": "If fake, state the truth or note that it's likely a scam/AI-generated.",
  "data_points": {
     "labels": ["Human Written", "Factual Accuracy", "Source Credibility", "Logic & Consistency", "Safety"],
     "values": [number, number, number, number, number]
  }
}`;

  const body = {
    contents: [{ parts: [{ text: PROMPT + '\n\nNews: ' + text.trim() }] }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 8192, responseMimeType: 'application/json' }
  };

  try {
    console.log('📡 Calling Gemini API...');
    const { res: gemRes, ok, status, errText } = await callGeminiWithKeyRotation(body);

    if (!ok) {
      console.error(`❌ All keys failed. Last status: ${status}`);
      return res.status(200).json({
        verdict: 'UNKNOWN',
        confidence: 0,
        explanation: 'Service temporarily unavailable. All API keys are rate-limited. Please wait 1-2 minutes and try again.',
        corrected_fact: '',
        data_points: { labels: ['Human Written', 'Factual Accuracy', 'Source Credibility', 'Logic & Consistency', 'Safety'], values: [0, 0, 0, 0, 0] },
        engine: 'gemini',
        error_hint: 'quota_exceeded'
      });
    }

    const { parsed, error: parseError } = await parseGeminiResponse(gemRes);
    if (parseError) return res.status(502).json({ error: parseError });

    const verdict = parsed.verdict === 'FAKE' ? 'FAKE' : 'REAL';
    let confidence = Math.max(0, Math.min(100, Number(parsed.confidence) || 0));
    const explanation = typeof parsed.explanation === 'string' ? parsed.explanation : 'No explanation provided.';
    const corrected_fact = verdict === 'FAKE' && typeof parsed.corrected_fact === 'string' ? parsed.corrected_fact : '';
    let data_points = { labels: [], values: [] };
    if (parsed.data_points && Array.isArray(parsed.data_points.labels) && Array.isArray(parsed.data_points.values)) {
      data_points = { labels: parsed.data_points.labels, values: parsed.data_points.values };
    }

    console.log(`✅ Result: ${verdict} (${confidence}%)`);
    return res.json({ verdict, confidence, explanation, corrected_fact, data_points, engine: 'gemini' });

  } catch (err) {
    console.error(`❌ Unexpected error: ${err.message}`);
    return res.status(500).json({ error: 'Internal server error: ' + err.message });
  }
});

// ─── POST /api/analyze-image — Legacy image endpoint ─────────────────────────
app.post('/api/analyze-image', async (req, res) => {
  const { base64, mimeType } = req.body;
  if (!base64) return res.status(400).json({ error: 'No image provided.' });
  if (API_KEYS.length === 0) return res.status(500).json({ error: 'No API keys configured.' });

  const PROMPT = `You are a strict AI image analysis expert. Analyze the image.
1. Determine if it is AI-generated or captured by a human.
2. Check for adult/NSFW content.
3. Check for fake/deepfake content.

Return ONLY valid JSON format:
{
  "verdict": "REAL",
  "generated_by": "Human",
  "confidence": 95,
  "adult_content": false,
  "fake_content": false,
  "explanation": "Clear reason.",
  "data_points": {
     "labels": ["AI Indicators", "Human Generation", "Adult Content Risk", "Fake Content Risk"],
     "values": [5, 95, 0, 0]
  }
}`;

  const body = {
    contents: [{ parts: [{ text: PROMPT }, { inlineData: { mimeType: mimeType || 'image/jpeg', data: base64 } }] }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 8192, responseMimeType: 'application/json' }
  };

  try {
    const { res: gemRes, ok, status } = await callGeminiWithKeyRotation(body);

    if (!ok) {
      return res.status(200).json({
        verdict: 'UNKNOWN', confidence: 0,
        explanation: 'Service temporarily unavailable. Please wait 1-2 minutes and try again.',
        engine: 'gemini', error_hint: 'quota_exceeded'
      });
    }

    const { parsed, error: parseError } = await parseGeminiResponse(gemRes);
    if (parseError) return res.status(502).json({ error: parseError });

    const verdict = (parsed.verdict === 'FAKE' || parsed.generated_by === 'AI' || parsed.fake_content) ? 'FAKE' : 'REAL';
    let confidence = Math.max(0, Math.min(100, Number(parsed.confidence) || 0));
    const generated_by = parsed.generated_by === 'AI' ? 'AI' : 'Human';
    const customTitle = generated_by === 'AI' ? 'Generated by AI' : 'Generated by Human!';
    const explanation = typeof parsed.explanation === 'string' ? parsed.explanation : 'No explanation.';
    const combined = explanation + '\n\n' + (parsed.adult_content ? '⚠️ Adult Content Detected!' : '✅ No Adult Content') + '\n' + (parsed.fake_content ? '⚠️ Fake Content Detected!' : '✅ Authentic Content');
    let data_points = { labels: [], values: [] };
    if (parsed.data_points && Array.isArray(parsed.data_points.labels)) data_points = parsed.data_points;

    return res.json({ verdict, confidence, explanation: combined, customTitle, adult_content: !!parsed.adult_content, fake_content: !!parsed.fake_content, data_points, engine: 'gemini' });
  } catch (err) {
    return res.status(500).json({ error: 'Internal server error: ' + err.message });
  }
});

// ─── POST /api/analyze/image — Full forensics image analysis ─────────────────
app.post('/api/analyze/image', async (req, res) => {
  const { imageBase64, mimeType } = req.body;
  if (!imageBase64) return res.status(400).json({ error: 'No imageBase64 provided.' });
  if (API_KEYS.length === 0) return res.status(500).json({ error: 'No API keys configured.' });

  const PROMPT = `Analyze this image. Return ONLY this JSON:
{
  "ai_verdict": "AI_GENERATED or HUMAN_CREATED",
  "ai_confidence": "0-100",
  "ai_indicators": ["indicator1", "indicator2"],
  "ai_explanation": "2 sentence explanation",
  "content_safety": {
    "adult_content": false,
    "violence": false,
    "fake_person": false,
    "hate_content": false,
    "misleading": false,
    "overall_safe": true
  },
  "content_flags": [],
  "image_scores": {
    "labels": ["Face Naturalness", "Background", "Lighting", "Texture"],
    "values": [80, 80, 80, 80]
  },
  "summary": "one sentence"
}
Rules: AI_GENERATED if Midjourney/DALL-E style. HUMAN_CREATED if real photograph. Return ONLY JSON. Nothing else.`;

  const body = {
    contents: [{
      parts: [
        { inlineData: { mimeType: mimeType || 'image/jpeg', data: imageBase64 } },
        { text: PROMPT }
      ]
    }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 8192, responseMimeType: 'application/json' }
  };

  try {
    console.log('📡 Calling Gemini Vision API...');
    const { res: gemRes, ok, status, errText } = await callGeminiWithKeyRotation(body);

    if (!ok) {
      console.error(`❌ All keys failed for image analysis.`);
      return res.status(200).json({
        ai_verdict: 'UNKNOWN', ai_confidence: 0,
        ai_indicators: [],
        ai_explanation: 'Service temporarily unavailable. All API keys are rate-limited. Please wait 1-2 minutes and try again.',
        content_safety: { adult_content: false, violence: false, fake_person: false, hate_content: false, misleading: false, overall_safe: true },
        content_flags: [],
        image_scores: { labels: ['Face Naturalness', 'Background Consistency', 'Lighting Coherence', 'Texture Realism'], values: [50, 50, 50, 50] },
        summary: 'Analysis unavailable — API quota exceeded.',
        engine: 'gemini', error_hint: 'quota_exceeded'
      });
    }

    const { parsed, error: parseError } = await parseGeminiResponse(gemRes);
    if (parseError) return res.status(502).json({ error: parseError });

    const ai_verdict = parsed.ai_verdict === 'AI_GENERATED' ? 'AI_GENERATED' : 'HUMAN_CREATED';
    let ai_confidence = Math.max(0, Math.min(100, Number(parsed.ai_confidence) || 50));
    const ai_indicators = Array.isArray(parsed.ai_indicators) ? parsed.ai_indicators : [];
    const ai_explanation = typeof parsed.ai_explanation === 'string' ? parsed.ai_explanation : 'Analysis complete.';
    const cs = parsed.content_safety || {};
    const content_safety = {
      adult_content: !!cs.adult_content, violence: !!cs.violence,
      fake_person: !!cs.fake_person, hate_content: !!cs.hate_content,
      misleading: !!cs.misleading, overall_safe: cs.overall_safe !== undefined ? !!cs.overall_safe : true
    };
    const content_flags = Array.isArray(parsed.content_flags) ? parsed.content_flags : [];
    let image_scores = { labels: ['Face Naturalness', 'Background Consistency', 'Lighting Coherence', 'Texture Realism'], values: [50, 50, 50, 50] };
    if (parsed.image_scores && Array.isArray(parsed.image_scores.values)) {
      image_scores = { labels: parsed.image_scores.labels, values: parsed.image_scores.values.map(v => Math.max(1, Math.min(100, Number(v) || 50))) };
    }
    const summary = typeof parsed.summary === 'string' ? parsed.summary : `${ai_verdict.replace('_', ' ')}.`;

    console.log(`✅ Forensics Result: ${ai_verdict} (${ai_confidence}% confidence)`);
    return res.json({ ai_verdict, ai_confidence, ai_indicators, ai_explanation, content_safety, content_flags, image_scores, summary, engine: 'gemini' });

  } catch (err) {
    console.error(`❌ Unexpected error: ${err.message}`);
    return res.status(500).json({ error: 'Internal server error: ' + err.message });
  }
});

// ─── POST /api/analyze/research — Fake research detection ────────────────────
app.post('/api/analyze/research', async (req, res) => {
  const { text, url } = req.body;
  const content = (text || '') + (url ? `\n\nURL Reference: ${url}` : '');
  if (!content.trim()) return res.status(400).json({ error: 'No research content provided.' });
  if (API_KEYS.length === 0) return res.status(500).json({ error: 'No API keys configured.' });

  const PROMPT = `You are an expert scientific fact-checker and research paper authenticity analyzer.

Analyze the given research claim or abstract for:
1. Scientific accuracy and credibility
2. Statistical validity of claims
3. Methodology soundness
4. Citation and peer review indicators
5. Red flags: extraordinary claims, conflict of interest, predatory journal signs, correlation vs causation errors, cherry-picked data, small sample sizes

Return ONLY valid JSON (no markdown):
{
  "verdict": "CREDIBLE" or "QUESTIONABLE" or "DEBUNKED",
  "confidence": integer 0-100,
  "explanation": "2-3 sentence analysis",
  "credibility_score": integer 0-100,
  "methodology_score": integer 0-100,
  "evidence_score": integer 0-100,
  "peer_review_likelihood": integer 0-100,
  "consensus_score": integer 0-100,
  "red_flags": ["flag1", "flag2"],
  "supporting_facts": ["fact1", "fact2"],
  "corrected_fact": "real scientific consensus if DEBUNKED, empty string otherwise",
  "data_points": {
    "labels": ["Credibility","Methodology","Evidence","Peer Review","Consensus"],
    "values": [score1, score2, score3, score4, score5]
  }
}

Research content to analyze:\n`;

  const body = {
    contents: [{ parts: [{ text: PROMPT + content.trim() }] }],
    generationConfig: { temperature: 0.1, maxOutputTokens: 8192, responseMimeType: 'application/json' }
  };

  try {
    console.log('📡 Calling AI for research analysis...');
    const { res: gemRes, ok, status, errText } = await callGeminiWithKeyRotation(body);

    if (!ok) {
      return res.status(200).json({
        verdict: 'QUESTIONABLE', confidence: 0,
        explanation: 'Service temporarily unavailable. Please try again in a few minutes.',
        credibility_score: 0, methodology_score: 0, evidence_score: 0, peer_review_likelihood: 0, consensus_score: 0,
        red_flags: [], supporting_facts: [], corrected_fact: '',
        data_points: { labels: ['Credibility','Methodology','Evidence','Peer Review','Consensus'], values: [0,0,0,0,0] },
        engine: 'gemini', error_hint: 'quota_exceeded'
      });
    }

    const { parsed, error: parseError } = await parseGeminiResponse(gemRes);
    if (parseError) return res.status(502).json({ error: parseError });

    const verdict = ['CREDIBLE','QUESTIONABLE','DEBUNKED'].includes(parsed.verdict) ? parsed.verdict : 'QUESTIONABLE';
    const confidence = Math.max(0, Math.min(100, Number(parsed.confidence) || 50));
    const explanation = parsed.explanation || 'Analysis complete.';
    const credibility_score = Math.max(0, Math.min(100, Number(parsed.credibility_score) || 50));
    const methodology_score = Math.max(0, Math.min(100, Number(parsed.methodology_score) || 50));
    const evidence_score = Math.max(0, Math.min(100, Number(parsed.evidence_score) || 50));
    const peer_review_likelihood = Math.max(0, Math.min(100, Number(parsed.peer_review_likelihood) || 50));
    const consensus_score = Math.max(0, Math.min(100, Number(parsed.consensus_score) || 50));
    const red_flags = Array.isArray(parsed.red_flags) ? parsed.red_flags : [];
    const supporting_facts = Array.isArray(parsed.supporting_facts) ? parsed.supporting_facts : [];
    const corrected_fact = typeof parsed.corrected_fact === 'string' ? parsed.corrected_fact : '';
    let data_points = { labels: ['Credibility','Methodology','Evidence','Peer Review','Consensus'], values: [credibility_score, methodology_score, evidence_score, peer_review_likelihood, consensus_score] };
    if (parsed.data_points?.labels && Array.isArray(parsed.data_points.values)) data_points = parsed.data_points;

    console.log(`✅ Research Result: ${verdict} (${confidence}%)`);
    return res.json({ verdict, confidence, explanation, credibility_score, methodology_score, evidence_score, peer_review_likelihood, consensus_score, red_flags, supporting_facts, corrected_fact, data_points, engine: 'gemini' });

  } catch (err) {
    return res.status(500).json({ error: 'Internal server error: ' + err.message });
  }
});

// ─── POST /api/analyze/weather — Weather prediction checker ──────────────────
app.post('/api/analyze/weather', async (req, res) => {
  const { city, prediction, predictedTempMin, predictedTempMax, predictedHumidity, predictedWind } = req.body;
  if (!city || !prediction) return res.status(400).json({ error: 'City and prediction are required.' });

  const WEATHER_API_KEY = 'f01aef374fdade0e1e8d9d284ee7b2c7';

  try {
    console.log(`🌤️ Fetching weather for: ${city}`);
    const weatherRes = await fetch(
      `https://api.openweathermap.org/data/2.5/weather?q=${encodeURIComponent(city)}&appid=${WEATHER_API_KEY}&units=metric`
    );

    if (!weatherRes.ok) {
      const errData = await weatherRes.json();
      return res.status(400).json({ error: errData.message || 'City not found. Please check the city name.' });
    }

    const w = await weatherRes.json();

    const actualTemp = Math.round(w.main.temp * 10) / 10;
    const actualHumidity = w.main.humidity;
    const actualWindSpeed = Math.round(w.wind.speed * 3.6 * 10) / 10; // m/s → km/h
    const actualWeatherMain = w.weather[0].main; // Clear, Rain, Snow, ...
    const actualDescription = w.weather[0].description;
    const actualFeelsLike = Math.round(w.main.feels_like * 10) / 10;
    const actualPressure = w.main.pressure;
    const actualVisibility = Math.round((w.visibility || 10000) / 1000 * 10) / 10;
    const icon = w.weather[0].icon;
    const cityName = w.name;
    const country = w.sys.country;
    const sunrise = w.sys.sunrise;
    const sunset = w.sys.sunset;

    // Map user prediction to weather conditions
    const predictionMap = {
      'Sunny': ['Clear'],
      'Rainy': ['Rain', 'Drizzle'],
      'Snowing': ['Snow'],
      'Thunderstorm': ['Thunderstorm'],
      'Foggy': ['Fog', 'Mist', 'Haze', 'Smoke', 'Dust'],
      'Windy': ['__wind__'],
      'Partly Cloudy': ['Clouds'],
      'Clear': ['Clear']
    };

    const matchConditions = predictionMap[prediction] || [];
    let weatherCorrect = false;
    if (prediction === 'Windy') {
      weatherCorrect = actualWindSpeed > 30;
    } else {
      weatherCorrect = matchConditions.some(c => actualWeatherMain.toLowerCase().includes(c.toLowerCase()));
    }

    const weatherAccuracy = weatherCorrect ? 100 : 20;

    const predictedTempAvg = ((Number(predictedTempMin) || 20) + (Number(predictedTempMax) || 30)) / 2;
    const tempDiff = Math.abs(predictedTempAvg - actualTemp);
    const tempAccuracy = tempDiff < 3 ? 100 : tempDiff < 6 ? 85 : tempDiff < 10 ? 70 : Math.max(10, 50 - tempDiff * 2);

    const humidityDiff = Math.abs((Number(predictedHumidity) || 50) - actualHumidity);
    const humidityAccuracy = humidityDiff < 10 ? 100 : humidityDiff < 20 ? 80 : Math.max(10, 60 - humidityDiff);

    const windDiff = Math.abs((Number(predictedWind) || 10) - actualWindSpeed);
    const windAccuracy = windDiff < 10 ? 100 : windDiff < 25 ? 75 : Math.max(10, 50 - windDiff / 2);

    const overallAccuracy = Math.round(
      weatherAccuracy * 0.4 +
      tempAccuracy * 0.3 +
      humidityAccuracy * 0.15 +
      windAccuracy * 0.15
    );

    const verdict = overallAccuracy >= 75 ? 'CORRECT' : overallAccuracy >= 50 ? 'PARTIALLY_CORRECT' : 'INCORRECT';

    console.log(`✅ Weather Result: ${verdict} (${overallAccuracy}% accuracy) for ${cityName}`);

    return res.json({
      verdict,
      overallAccuracy,
      weatherMatch: weatherCorrect,
      actual: {
        temp: actualTemp, feelsLike: actualFeelsLike, humidity: actualHumidity,
        windSpeed: actualWindSpeed, pressure: actualPressure, visibility: actualVisibility,
        description: actualDescription, weatherMain: actualWeatherMain,
        icon, sunrise, sunset, cityName, country
      },
      predicted: {
        weatherType: prediction,
        tempMin: Number(predictedTempMin) || 20,
        tempMax: Number(predictedTempMax) || 30,
        humidity: Number(predictedHumidity) || 50,
        wind: Number(predictedWind) || 10
      },
      comparison: {
        tempDiff: Math.round((actualTemp - predictedTempAvg) * 10) / 10,
        humidityDiff: actualHumidity - (Number(predictedHumidity) || 50),
        windDiff: Math.round((actualWindSpeed - (Number(predictedWind) || 10)) * 10) / 10,
        weatherCorrect
      },
      accuracy: {
        weather: weatherAccuracy,
        temperature: Math.round(tempAccuracy),
        humidity: Math.round(humidityAccuracy),
        wind: Math.round(windAccuracy)
      },
      data_points: {
        labels: ['Weather','Temperature','Humidity','Wind Speed'],
        values: [weatherAccuracy, Math.round(tempAccuracy), Math.round(humidityAccuracy), Math.round(windAccuracy)]
      }
    });

  } catch (err) {
    console.error(`❌ Weather error: ${err.message}`);
    return res.status(500).json({ error: 'Failed to fetch weather data: ' + err.message });
  }
});

// ─── Health check ─────────────────────────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({ status: 'ok', model: MODEL, keys: API_KEYS.length, keyLoaded: API_KEYS.length > 0 });
});

// ─── Start server ─────────────────────────────────────────────────────────────
app.listen(PORT, () => {
  console.log(`🚀 TruthGuard running on http://localhost:${PORT}`);
  console.log(`🔑 Keys loaded: ${API_KEYS.length}/3`);
  console.log(`🤖 Model: ${MODEL}`);
  console.log('✅ Server ready!');
});
